// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        // Note: Xposed API dependency is typically provided by the Xposed framework at runtime
        // For development/build purposes, the API stubs may need to be obtained manually
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
